import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import localFont from "next/font/local";
import "./globals.css";

//chack if the user is loged in or not
import { getServerSession } from "next-auth";
import SessionProvider from "@/app/utils/SessionProvider"
import Footer from "@/components/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-white`}
      >
        <SessionProvider session={session}>
          <div >
            <Navbar />
            {children}
          </div>

        </SessionProvider>
      </body>
    </html>
  );
}
